# Generated by Django 2.1.7 on 2019-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.CharField(max_length=20)),
                ('catname', models.CharField(max_length=20)),
                ('catparentid', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Shoping',
            },
        ),
    ]
