# Generated by Django 2.1.7 on 2019-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orkut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Age',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='student',
            name='FirstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='LastName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
