# Generated by Django 2.1.7 on 2019-02-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsession', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myform',
            new_name='myformsession',
        ),
    ]
